name: Cleanup Preview artifacts

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: gacts/github-slug@dec25aaca578647a666efc0b20774831ff19612c
        id: slug
      - name: test
        run: echo ${{ steps.slug.outputs.branch-name-slug }}
      - name: env
        run: env
